hassio-addons/addon-jupyterlab

jupyterlab/rootfs/etc/cont-init.d/20-notebooks-dir.sh

Link the HA Getting Started notebook so it's easier to get started
User experience
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

Link HA Getting Started in books root

---

LICENSE.md
README.md
jupyterlab/.README.j2
jupyterlab/DOCS.md

Happy New Year

---

README.md

Fixes broken architecture badge, also updates them to reflect the current state 😄

Tweak badges in documentation

---

jupyterlab/Dockerfile

:arrow_up: Upgrades libpq5 to 11.10-0+deb10u1

---

jupyterlab/Dockerfile

Upgrades nodejs to 12.20.2-1nodesource1

:arrow_up: Upgrades nodejs to 12.20.2-1nodesource1

---

jupyterlab/Dockerfile

Upgrades nodejs to 12.21.0-1nodesource1

:arrow_up: Upgrades nodejs to 12.21.0-1nodesource1

---

jupyterlab/Dockerfile

Upgrades libpq5 to 11.11-0+deb10u1

⬆️ Upgrades libpq5 to 11.11-0+deb10u1

---

jupyterlab/Dockerfile

Upgrades libssl-dev to 1.1.1d-0+deb10u6

⬆️ Upgrades libssl-dev to 1.1.1d-0+deb10u6

---

jupyterlab/Dockerfile

Upgrades nodejs to 12.22.0-1nodesource1

⬆️ Upgrades nodejs to 12.22.0-1nodesource1

---

jupyterlab/Dockerfile

⬆️ Upgrades numpy to 1.20.2

---

jupyterlab/Dockerfile

Upgrades libpq5 to 13.5-0+deb11u1

⬆️ Upgrades libpq5 to 13.5-0+deb11u1

---

jupyterlab/Dockerfile

Upgrades nodejs to 14.19.1-deb-1nodesource1

⬆️ Upgrades nodejs to 14.19.1-deb-1nodesource1

---

jupyterlab/Dockerfile
jupyterlab/build.yaml

Upgrades add-on base image to 5.3.0

⬆️ Upgrades add-on base image to 5.3.0

---

.github/workflows/deploy.yaml
jupyterlab/build.yaml
jupyterlab/config.yaml

Sign add-on with Codenotary Community Attestation Service (CAS)

:lock: Sign add-on with Codenotary Community Attestation Service (CAS)

---

jupyterlab/DOCS.md

Add My buttons to documentation, making it easier to find the add-on

:books: Add My buttons to documentation

---

jupyterlab/rootfs/etc/services.d/nginx/finish

Fixes the NGINX finish script (missed in the previous PR)

🚑 Fix NGINX service finish script

---

jupyterlab/DOCS.md

:books: Use new My Home Assistant link format

---

jupyterlab/Dockerfile
jupyterlab/build.yaml

Upgrades add-on base image to 6.1.1

⬆️ Upgrades add-on base image to 6.1.1

---

jupyterlab/Dockerfile
jupyterlab/build.yaml

Upgrades add-on base image to 6.1.2

⬆️ Upgrades add-on base image to 6.1.2

---

jupyterlab/Dockerfile

⬆️ Upgrades nodejs to 14.20.1-deb-1nodesource1

---

jupyterlab/Dockerfile

⬆️ Upgrades nodejs to 14.21.1-deb-1nodesource1

---

jupyterlab/Dockerfile
jupyterlab/build.yaml

Updates the add-on base image to 6.2.0

⬆️ Upgrades add-on base image to 6.2.0

---

jupyterlab/Dockerfile

⬆️ Upgrades libxml2 to 2.9.10+dfsg-6.7+deb11u3

---

jupyterlab/Dockerfile

⬆️ Upgrades nodejs to 14.21.3-deb-1nodesource1

---

LICENSE.md
README.md
jupyterlab/.README.j2
jupyterlab/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

jupyterlab/Dockerfile

⬆️ Upgrades libpq5 to 13.10-0+deb11u1

---

LICENSE.md
README.md
jupyterlab/.README.j2
jupyterlab/DOCS.md

:fireworks: Updates maintenance/license year to 2024

---

jupyterlab/Dockerfile

⬆️ Upgrades libpq5 to 15.7-0+deb12u1

---

LICENSE.md
README.md
jupyterlab/.README.j2
jupyterlab/DOCS.md

:fireworks: Updates maintenance/license year to 2025

---

jupyterlab/Dockerfile

:arrow_up: Upgrades nginx to 1.22.1-9+deb12u2

---

jupyterlab/Dockerfile

:arrow_up: Upgrades libssl-dev to 3.0.16-1~deb12u1
